title: cloudpost
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cloudpost.online" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  deancommasteven

# Build settings
theme: minima
#plugins:
#  - jekyll-feed
